### ISSUE TITLE
CentOS 7 下 include http-flv.conf 报错

### ISSUE THREAD

**Issue by xzzh999** [winshining/nginx-http-flv-module-packages#1]
Hi~

版本:

        nginx-1.14.0-1.el7_4.ngx.x86_64
        nginx-http-flv-module-1.2.4-1.el7.x86_64
        nginx-release-centos-7-0.el7.ngx.noarch

系统:

        CentOS Linux release 7.2.1511 (Core)

报错内容:

     nginx: [emerg] unknown directive "flv_live" in /etc/nginx/http-flv/http-flv.conf:7

**Comment by winshining** [comment]
/usr/share/nginx/modules目录下有mod-http-flv.conf么？
/usr/lib64/nginx/modules目录下有ngx_rtmp_module.so么？

**Comment by xzzh999** [comment]
@winshining 都有的，而且 nginx 确认包含 flv 模块:

`nginx version: nginx/1.14.0
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -pie'`

conf 目前都是安装后的默认配置

**Comment by winshining** [comment]
nginx本身有ngx_http_flv_module，但是那个只是点播的，nginx-http-flv-module是在nginx-rtmp-module基础上开发的，跟nginx那个http_flv模块没有关系。
再看看/etc/nginx/nginx.conf里的events配置项前有没有这一句：

    include /usr/share/nginx/modules/*.conf;

如果没有，把它加上去。记住，必须在events配置项前加，不然nginx启动会报错。

**Comment by xzzh999** [comment]
@winshining  没有，加上之后现在是报这个:

`nginx: [emerg] module "/usr/lib64/nginx/modules/ngx_rtmp_module.so" version 1012002 instead of 1014000 in /usr/share/nginx/modules/mod-http-flv.conf:1
`

**Comment by winshining** [comment]
安装nginx-1.12.2吧，版本不匹配，我打包的时候系统上yum安装的是nginx-1.12.2

**Comment by xzzh999** [comment]
@winshining 感谢!
